[pytest]
addopts =
#    --headed
    --screenshot=only-on-failure
    --video=retain-on-failure
    --tracing=retain-on-failure
    -v --alluredir=allure-results
markers =
    smoke: smoke tests
    regression: regression tests
testpaths =
    tests
